version: "3"

services:
  backend:
    build:
      context: ./
      dockerfile: ./src/Dockerfile
    env_file:
      - .env
    container_name: backend
    depends_on:
#      - mongodb
      - db
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["docker/run.sh"]
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=contest
      - MONGO_INITDB_ROOT_PASSWORD=contest

  db:
      image: postgres
      env_file:
        - .env
      volumes:
        - db_vol:/var/lib/postgresql/data
      ports:
        - "5432:5432"

  redis:
    image: "redis:alpine"
    ports:
     - "6379:6379"

  flower:
    restart: always
    build:
      context: ./
      dockerfile: src/Dockerfile
    command: ["docker/celery.sh", "flower"]
    volumes:
      - .:/app
    environment:
      - C_FORCE_ROOT=true
    env_file:
      - .env
    ports:
     - "5555:5555"
    depends_on:
      - backend
      - redis
      - db

  celery:
    restart: always
    build:
      context: ./
      dockerfile: src/Dockerfile
    command: ["docker/celery.sh", "celery"]
    volumes:
      - .:/app
    environment:
      - C_FORCE_ROOT=true
    env_file:
      - .env
    depends_on:
      - backend
      - redis
      - db
volumes:
  db_vol:

  #rabbit:
