"""fix

Revision ID: 826963568097
Revises: bbdb4b416aa2
Create Date: 2023-05-06 01:22:48.151533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '826963568097'
down_revision = 'bbdb4b416aa2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
