"""relationship

Revision ID: def2fd0d0ade
Revises: a18c344e4ecc
Create Date: 2023-05-08 22:40:30.475580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'def2fd0d0ade'
down_revision = 'a18c344e4ecc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
