"""Tasks added

Revision ID: 5e30e55ee1ea
Revises: d2cda0202e1e
Create Date: 2023-05-05 23:52:43.021669

"""
from alembic import op
import sqlalchemy as sa

from src.utils import ChoiceType
from src.tasks.utils import StatusEnum


# revision identifiers, used by Alembic.
revision = '5e30e55ee1ea'
down_revision = 'd2cda0202e1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('topic', sa.Integer(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic'], ['topic.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task', sa.Integer(), nullable=True),
    sa.Column('tag', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tag'], ['tag.id'], ),
    sa.ForeignKeyConstraint(['task'], ['task.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task', sa.Integer(), nullable=True),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(), nullable=True),
    sa.Column('status', ChoiceType(dict(map(lambda item: (item.name, item.value), StatusEnum))), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['task'], ['task.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_task')
    op.drop_table('task_tag')
    op.drop_table('task')
    op.drop_table('topic')
    op.drop_table('tag')
    # ### end Alembic commands ###
