"""Fix relationships

Revision ID: bbdb4b416aa2
Revises: 5e30e55ee1ea
Create Date: 2023-05-06 01:19:45.865168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbdb4b416aa2'
down_revision = '5e30e55ee1ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_topic_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'topic')
    op.drop_constraint('task_tag_tag_fkey', 'task_tag', type_='foreignkey')
    op.drop_constraint('task_tag_task_fkey', 'task_tag', type_='foreignkey')
    op.drop_column('task_tag', 'task')
    op.drop_column('task_tag', 'tag')
    op.drop_constraint('user_task_user_fkey', 'user_task', type_='foreignkey')
    op.drop_constraint('user_task_task_fkey', 'user_task', type_='foreignkey')
    op.drop_column('user_task', 'user')
    op.drop_column('user_task', 'task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_task', sa.Column('task', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('user_task', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_task_task_fkey', 'user_task', 'task', ['task'], ['id'])
    op.create_foreign_key('user_task_user_fkey', 'user_task', 'user', ['user'], ['id'])
    op.add_column('task_tag', sa.Column('tag', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('task_tag', sa.Column('task', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_tag_task_fkey', 'task_tag', 'task', ['task'], ['id'])
    op.create_foreign_key('task_tag_tag_fkey', 'task_tag', 'tag', ['tag'], ['id'])
    op.add_column('task', sa.Column('topic', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_topic_fkey', 'task', 'topic', ['topic'], ['id'])
    # ### end Alembic commands ###
